# for debug
python -m torch.distributed.launch --nproc_per_node 2 --master_port 6009 run_train.py --overwrite_output_dir \
    --task_name sum --dataset_name concode \
    --train_data_path /weizhou_data/generation/UniXcoder/code-generation/data/concode \
    --dev_data_path /weizhou_data/generation/UniXcoder/code-generation/data/concode \
    --test_data_path /weizhou_data/generation/UniXcoder/code-generation/data/concode \
    --load_tokenized_data False \
    --generator_supervised True --generator_supervised_lambda 1.0 \
    --reranker_reward_scaler 1.5 --metric_reward_scaler 1.5 \
    --evaluate_generator True --generate_eval_candidates True --generate_candidate_strategy beamsearch \
    --use_baseline_reward True --training_mode iterative \
    --generator_num_cand_generated 8 --generator_num_cand_picked 8 \
    --num_cand_generated 16 --num_cand_picked 3 --candidate_pick_strategy bottom \
    --loss_type contrastive \
    --do_train True --do_eval True --do_predict True --prediction_loss_only False \
    --per_device_train_batch_size 2 --per_device_eval_batch_size 4 \
    --gradient_accumulation_steps 4 \
    --generator_learning_rate 5e-5 --reranker_learning_rate 1e-5 --warmup_ratio 0 \
    --num_train_epochs 3 \
    --evaluation_strategy steps --eval_steps 1000 \
    --logging_strategy steps --logging_steps 500 \
    --save_strategy steps --save_steps 1000 --save_total_limit 40 \
    --iteration_steps 1000 --iteration_reranker_steps 0 \
    --load_best_model_at_end True \
    --metric_for_best_model generator_eval_rouge1 --greater_is_better True \
    --reranker_model_name_or_path /weizhou_data/models/unixcoder-base \
    --generator_model_name_or_path /weizhou_data/models/unixcoder-base \
    --generator_checkpoint_dir /weizhou_data/generation/UniXcoder/code-generation/saved_models \
    --output_dir /weizhou_data/generation/UniXcoder/RLRanker_v7-code/saves/v7-debug \
    --generator_max_source_length 350 --reranker_max_source_length 350 --generator_max_target_length 150 --reranker_max_target_length 150 \
    --cache_data \
    --disable_tqdm True 

# single gpu
CUDA_VISIBLE_DEVICES="" python  run_train.py --overwrite_output_dir \
    --task_name sum --dataset_name concode \
    --train_data_path /weizhou_data/generation/UniXcoder/code-generation/data/concode \
    --dev_data_path /weizhou_data/generation/UniXcoder/code-generation/data/concode \
    --test_data_path /weizhou_data/generation/UniXcoder/code-generation/data/concode \
    --load_tokenized_data False \
    --generator_supervised True --generator_supervised_lambda 1.0 \
    --reranker_reward_scaler 1.5 --metric_reward_scaler 1.5 \
    --evaluate_generator True --generate_eval_candidates True --generate_candidate_strategy beamsearch \
    --use_baseline_reward True --training_mode iterative \
    --generator_num_cand_generated 2 --generator_num_cand_picked 2 \
    --num_cand_generated 16 --num_cand_picked 3 --candidate_pick_strategy bottom \
    --loss_type contrastive \
    --do_train True --do_eval True --do_predict True --prediction_loss_only False \
    --per_device_train_batch_size 2 --per_device_eval_batch_size 4 \
    --gradient_accumulation_steps 4 \
    --generator_learning_rate 5e-5 --reranker_learning_rate 1e-5 --warmup_ratio 0 \
    --num_train_epochs 3 \
    --evaluation_strategy steps --eval_steps 1000 \
    --logging_strategy steps --logging_steps 500 \
    --save_strategy steps --save_steps 1000 --save_total_limit 40 \
    --iteration_steps 1000 --iteration_reranker_steps 0 \
    --load_best_model_at_end True \
    --metric_for_best_model generator_eval_rouge1 --greater_is_better True \
    --reranker_model_name_or_path /weizhou_data/models/unixcoder-base \
    --generator_model_name_or_path /weizhou_data/models/unixcoder-base \
    --generator_checkpoint_dir /weizhou_data/generation/UniXcoder/code-generation/saved_models \
    --output_dir /weizhou_data/generation/UniXcoder/RLRanker_v7-code/saves/v7-debug \
    --generator_max_source_length 350 --reranker_max_source_length 350 --generator_max_target_length 150 --reranker_max_target_length 150 \
    --cache_data \
    --disable_tqdm True

# no warmup
python -m torch.distributed.launch --nproc_per_node 2 --master_port 6009 run_train.py --overwrite_output_dir \
    --task_name sum --dataset_name concode \
    --train_data_path /weizhou_data/generation/UniXcoder/code-generation/data/concode \
    --dev_data_path /weizhou_data/generation/UniXcoder/code-generation/data/concode \
    --test_data_path /weizhou_data/generation/UniXcoder/code-generation/data/concode \
    --load_tokenized_data False \
    --generator_supervised True --generator_supervised_lambda 1.0 \
    --reranker_reward_scaler 1.5 --metric_reward_scaler 1.5 \
    --evaluate_generator True --generate_eval_candidates True --generate_candidate_strategy beamsearch \
    --use_baseline_reward True --training_mode iterative \
    --generator_num_cand_generated 2 --generator_num_cand_picked 2 \
    --num_cand_generated 16 --num_cand_picked 3 --candidate_pick_strategy bottom \
    --loss_type contrastive \
    --do_train True --do_eval True --do_predict True --prediction_loss_only False \
    --per_device_train_batch_size 1 --per_device_eval_batch_size 4 \
    --gradient_accumulation_steps 4 \
    --generator_learning_rate 5e-5 --reranker_learning_rate 1e-5 --warmup_ratio 0 \
    --num_train_epochs 3 \
    --evaluation_strategy steps --eval_steps 1000 \
    --logging_strategy steps --logging_steps 500 \
    --save_strategy steps --save_steps 1000 --save_total_limit 40 \
    --iteration_steps 1000 --iteration_reranker_steps 0 \
    --load_best_model_at_end True \
    --metric_for_best_model generator_eval_rouge1 --greater_is_better True \
    --reranker_model_name_or_path /weizhou_data/models/unixcoder-base \
    --generator_model_name_or_path /weizhou_data/models/unixcoder-base \
    --output_dir /weizhou_data/generation/UniXcoder/RLRanker_v7-code/saves/v7-debug \
    --generator_max_source_length 350 --reranker_max_source_length 350 --generator_max_target_length 150 --reranker_max_target_length 150 \
    --cache_data \
    --disable_tqdm True 